### PR TITLE
SIEW-292 Update Municipio 2

### PR DESCRIPTION
**Pull request by JockeTF**
Reorganized version of #95.

Things to pay close attention to on UAC:
- Verify that Global Notice works as it should.
- Verify that Google Translate works on subsites.
- Verify that the search functionality works properly.
- Verify that the mobile menu works, especially the header button.
- Compare the printing layout to how it looks on production.
- Check if we should create a WCAG issue regaring the printing layout.
- Look over the general design of both the desktop and mobile layout.

### CODE REVIEW

**Comment by JockeTF** [comment]
@rsj10736 I have now rebased your commits into the other ones!

**Comment by JockeTF** [comment]
- Check what `ajax.js` does in Municipio.
- Check what happaned to `SingleEvent.php`.

**Comment by rsj10736** [comment]
- Check event listing where used

**Comment by rsj10736** [comment]
>     * Check what happaned to `SingleEvent.php`.
This is related to the event plugin. It has most likely been moved into the plugin itself as planned by Hbg.

**Comment by rsj10736** [comment]
Event listing seems to break (both the archive and single view). Updating to the latest version of the event manager plugin does not resolve the issue.

**Comment by JockeTF** [comment]
@rsj10736 These changes look good to me.

Do you think they should be rebased into the rest of the stuff?

**Comment by rsj10736** [comment]
I could see 0776c4f going into 5dbe2a4. In my opinion 84682d3 should be kept in its own commit since it is more of a necessary complement to the new municipio changes + event plugin, rather than just a change from the old views to bem-views.

**Comment by JockeTF** [comment]
@rsj10736 On second thought, I think we should keep both as is!

I can still rebase them if you think it's a good idea though!

**Comment by rsj10736** [comment]
I'd vote for keeping both commits as is :+1:

**Pull request merged**
